server:
  port: 18080
spring:
  application:
    name: tanhua-sso
    #spring-cloud 注册中心
  cloud:
    nacos:
      server-addr: 192.168.136.160:8848

  redis:
    host: 192.168.136.160
    port: 6379

dubbo:
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.itheima.tanhua.web
  consumer:
    check: false
  cloud:
    subscribed-services: tanhua-dubbo-db
  application:
    logger: slf4j



tanhua:
  #阿里云  短信服务
#  sms:
#    singName:
#    templateCode:
#    accessKey:
#    secret:

  #阿里云对象存储服务配置
  oss:
    accessKey: LTAI5tBNqAPSAHaaahZ9GD7U
    secret: wD30J2wYhFUY2UDEP37U4h126YO9wq
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: tanhua1234512345
    url: https://tanhua1234512345.oss-cn-hangzhou.aliyuncs.com/

  # 百度人脸识别配置
  aip:
    appId: 27551102
    apiKey: 8dtVqR9o3eCefqmiL3FWpUjN
    secretKey: gQZb1aCVLTLWuvGXPUmUwGvXEqNGviYk


  huanxin:
    appkey: 1157220926140087#tanhua
    clientId: YXA6gXk6JG8eSPeALWI7yqTZ4g
    clientSecret: YXA6mUkEg3SLCqdsML7jJ-OeulMQF_g