server:
  port: 18081

spring:
  application:
    name: tanhua-app
  redis:
    host: 192.168.136.160
    port: 6379
  cloud:
    nacos:
      server-addr: 192.168.136.160:8848

  #小视频上传的大小限制
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    port: 28828
    name: dubbo
  consumer:
    check: false
  scan:
    base-packages: com.itheima.tanhua.web



tanhua:
  #阿里云对象存储服务配置
  oss:
    accessKey: LTAI5tBNqAPSAHaaahZ9GD7U
    secret: wD30J2wYhFUY2UDEP37U4h126YO9wq
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: tanhua1234512345
    url: https://tanhua1234512345.oss-cn-hangzhou.aliyuncs.com/


  huanxin:
    appkey: 1157220926140087#tanhua
    clientId: YXA6gXk6JG8eSPeALWI7yqTZ4g
    clientSecret: YXA6mUkEg3SLCqdsML7jJ-OeulMQF_g

#默认推荐列表
  default:
    recommend:
      users: 2,3,8,10,18,20,24,29,27,32,36,37,56,64,75,88

# 分布式文件系统FDFS配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 192.168.136.160:22122
  web-server-url: http://192.168.136.160:8888/